// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaleWebMvcApp.Data;

namespace SaleWebMvcApp.Migrations
{
    [DbContext(typeof(SaleWebMvcAppContext))]
    [Migration("20200915172803_OtherEntities")]
    partial class OtherEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SaleWebMvcApp.Models.Department", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("SaleWebMvcApp.Models.SalesRecord", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("amount");

                    b.Property<DateTime>("date");

                    b.Property<int>("saleStatus");

                    b.Property<int?>("sellerid");

                    b.HasKey("id");

                    b.HasIndex("sellerid");

                    b.ToTable("SaleRecord");
                });

            modelBuilder.Entity("SaleWebMvcApp.Models.Seller", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Departmentid");

                    b.Property<double>("baseSalary");

                    b.Property<DateTime>("birthDate");

                    b.Property<string>("email");

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.HasIndex("Departmentid");

                    b.ToTable("Seller");
                });

            modelBuilder.Entity("SaleWebMvcApp.Models.SalesRecord", b =>
                {
                    b.HasOne("SaleWebMvcApp.Models.Seller", "seller")
                        .WithMany("salesRecord")
                        .HasForeignKey("sellerid");
                });

            modelBuilder.Entity("SaleWebMvcApp.Models.Seller", b =>
                {
                    b.HasOne("SaleWebMvcApp.Models.Department")
                        .WithMany("sellers")
                        .HasForeignKey("Departmentid");
                });
#pragma warning restore 612, 618
        }
    }
}
